name: "Code Lens - Code Analyzer"
description: "Send repository data to Code Lens server"

inputs:
  token:
    description: "Code Lens - Project Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send repository metadata
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPO_URL: ${{ github.event.repository.html_url }}
        REPO_NAME: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        echo "Debugging GitHub context variables:"
        echo "REPO_URL: $REPO_URL"
        echo "REPO_NAME: $REPO_NAME"
        echo "BRANCH: $BRANCH"
        echo "COMMIT_SHA: $COMMIT_SHA"
        JSON=$(jq -n --arg url "$REPO_URL" --arg name "$REPO_NAME"  --arg branch "$BRANCH" --arg commit_sha "$COMMIT_SHA" '{url: $url, name: $name, branch: $branch, commit_sha: $commit_sha}')
        echo "JSON payload: $JSON"
        curl -X POST http://localhost/api/repositories -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d "$JSON"
